## Data Generation
Generate data by generating random integers, converting to binary representation, then dumping into array

In [83]:
import numpy as np
import re
np.random.seed(12345)
intrep = np.random.randint(0, 256)
print(intrep)
binrep = np.binary_repr(intrep, width=8)
print(binrep)
arrep = np.flip(np.array(re.split('',binrep)[1:-1], dtype=int))
print(arrep)

226
11100010
[0 1 0 0 0 1 1 1]


In [130]:
import numpy as np
import re
np.random.seed(12345)

ints = np.random.randint(0, 256, size=100_000)
A = ints.copy()[0:50_000].astype(np.int64)
B = ints.copy()[50_000:].astype(np.int64)
C = A*B.astype(np.int64)

Astr, Bstr, Cstr = np.empty(len(A), dtype=object), np.empty(len(A), dtype=object), np.empty(len(A), dtype=object)

for i in range(len(A)):
    Astr[i] = np.binary_repr(A[i], width=8)
    Bstr[i] = np.binary_repr(B[i], width=8)
    Cstr[i] = np.binary_repr(C[i], width=16)
print(Astr)

Aarr, Barr, Carr = np.empty((len(A),8), dtype=object), np.empty((len(A),8), dtype=object), np.empty((len(A),16), dtype=object)

for i in range(len(A)):
    Aarr[i] = np.flip(np.array(re.split('', Astr[i])[1:-1], dtype=int))
    Barr[i] = np.flip(np.array(re.split('', Bstr[i])[1:-1], dtype=int))
    Carr[i] = np.flip(np.array(re.split('', Cstr[i])[1:-1], dtype=int))
print(Aarr)

['11100010' '11100101' '00011101' ... '10001001' '11011001' '11110101']
[[0 1 0 ... 1 1 1]
 [1 0 1 ... 1 1 1]
 [1 0 1 ... 0 0 0]
 ...
 [1 0 0 ... 0 0 1]
 [1 0 0 ... 0 1 1]
 [1 0 1 ... 1 1 1]]
